name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            cd /home/azureuser/user-agent-tracker-front
            git pull origin main
            cd /home/azureuser/user-agent-tracker-backend
            docker-compose up -d --build --no-deps frontend
            docker-compose up -d --no-deps nginx
            docker image prune -f
